### ISSUE TITLE
Problem with {property} in message

### ISSUE THREAD

**Issue by Astimus** [serilog/serilog-filters-expressions#10]
I have filter by regular expression.
Logs with `{property}` in messageTemplate do not fall into logs.

For example,

```
// Printed
Log.Information("Hello {property}", "world");

//Not Printed
Log.Information("Hello world");
```

How this library works with such types of logs?

**Comment by merbla** [comment]
Hi @Astimus,

Do you have an example RegEx you are using given the above example?  Can you provide an example reproducing the issue?

Thanks.

**Comment by Astimus** [comment]
@merbla I've updated all librarys. And now all works great.
