### ISSUE TITLE
Json Configuration Question

### ISSUE THREAD

**Issue by NLI-KelbyHunt** [serilog/serilog-filters-expressions#13]
Currently trying to configure my `EventLog` sink to only include 1 specific classes logging events. I can get it to work in C# API but not the Json configuration. Below is what I have tried in using in my Json file.

API works.
```cs
var log = new LoggerConfiguration()
    .ReadFrom.Configuration(_configuration)
    .WriteTo.Logger(lc => lc
        .Filter.ByIncludingOnly(Matching.FromSource<BaseService>())
        .WriteTo.EventLog("SourceNameOmitted", "LogNameOmitted"))
    .CreateLogger();
```

Json configuration does not.
```json
"Serilog": {
    "MinimumLevel": "Debug",
    "Using": ["Serilog.Sinks.Console", "Serilog.Sinks.RollingFile", "Serilog.Sinks.EventLog"],
    "WriteTo": [
      {
        "Name": "Console"
      },
      {
        "Name": "RollingFile",
        "Args": {
          "pathFormat": "omitted",
          "retainedFileCountLimit": "omitted",
          "restrictedToMinimumLevel": "omitted",
          "outputTemplate": "omitted"
        }
      },
      {
        "Name": "EventLog",
        "Args": {
          "logName": "LogNameOmitted",
          "source": "LogSourceOmitted",
          "manageEventSource": true
        },
        "Filter": [
          {
            "Name": "ByIncludingOnly",
            "Args": {
              "expression": "SourceContext = 'BaseService.BaseService'"
            }
          }
        ]
      }
    ]
  }
```

My namespace is `BaseService` and the class I am trying to filter on in `IncludingOnly` is a class named `BaseService`.

Also no luck using [SerilogAnalyzer](https://github.com/Suchiman/SerilogAnalyzer). Not sure why I don't get the option to see the fluentapi translated to configuration. Possibly Resharper? but I disabled and tried without, still no luck.

**Comment by nblumhardt** [comment]
Hi @NLI-KelbyHunt - thanks for getting in touch, sorry about the slow reply.

I don't think Serilog Analyzer has support for `WriteTo.Logger` yet; it's a fairly new feature in the JSON configuration provider. I'll raise an issue over there shortly.

Your config has the filter under the event log sink's configuration node - to work, you need to mirror the configuration in code and have a `"Logger"` sink set up; see https://github.com/skomis-mm/serilog-settings-configuration/blob/b37c26500448288ca97bfe31f80f9c840aa07e0c/sample/Sample/appsettings.jsonfor an example.

Hope this helps!
