### ISSUE TITLE
Improper parsing of multiple logs

### ISSUE THREAD

**Issue by andymartin** [serilog/serilog-filters-expressions#17]
I have multiple logs which are configured using app settings. For example:

    <add key="console:serilog:using:Console" value="Serilog.Sinks.Console" />
    <add key="console:serilog:write-to:Console" />
    <add key="console:serilog:write-to:Console.restrictedToMinimumLevel" value="Verbose" />
    <add key="console:serilog:write-to:Console.outputTemplate" value="{Timestamp:yyyy-MM-dd HH:mm:ss,fff} [{ThreadId}] [{ProcessId}] {PaddedLogLevel:l} {SourceContext:l} [{EnvironmentUserName:l}@{MachineName:l}] - {Message}{NewLine:l}{Exception:l}{StackTrace}" />

These are loaded as:

`loggerConfiguration.ReadFrom.AppSettings("console");`

I have multiple custom logger configs using that configuration and all of them work correctly. I have configured only one for filtering:

    <add key="requests:serilog:using:SizeRollingFile" value="Serilog.Sinks.RollingFile.Extension" />
    <add key="requests:serilog:write-to:SizeRollingFile" />
    <add key="requests:serilog:write-to:SizeRollingFile.restrictedToMinimumLevel" value="Verbose" />
    <add key="requests:serilog:write-to:SizeRollingFile.pathFormat" value="FilteredLog.log" />
    <add key="requests:serilog:write-to:SizeRollingFile.outputTemplate" value="{Timestamp:yyyy-MM-dd HH:mm:ss,fff} [{ThreadId}] [{ProcessId}] {LogLevel:l} {SourceContext:l} [{EnvironmentUserName:l}@{MachineName:l}] - {Message}{NewLine:l}{Exception:l}{StackTrace}" />
    <add key="requests:serilog:write-to:SizeRollingFile.fileSizeLimitBytes" value="10490000" />
    <add key="requests:serilog:write-to:SizeRollingFile.retainedFileDurationLimit" value="04.00:00:00" />
    <add key="requests:serilog:using:FilterExpressions" value="Serilog.Filters.Expressions" />
    <add key="requests:serilog:filter:ByExcluding.expression" value="SourceContext &lt;&gt; 'RegionRequestLog'" />

The filter works correctly, however all logs are filtered, not just the one configured.

**Comment by tsimbalar** [comment]
Interesting 🤔 

Could you post the complete `*:serilog:*` `<appSettings>` (removing possibly sensitive information) of your configuration file, as well as the code for that creates your loggers ? 

Thanks !

**Comment by nblumhardt** [comment]
Hi Andy,

To achieve what you're looking for you'll need multiple logger pipelines; using `ReadFrom.AppSettings()` on the same pipeline multiple times will be additive, hence the two sections are just being combined.

You could try:

```csharp
Log.Logger = new LoggerConfiguration()
    .ReadFrom.AppSettings() // Global, serilog: settings, e.g. minimum level
    .WriteTo.Logger(lc => lc
        .ReadFrom.AppSettings("console"))
    .WriteTo.Logger(lc => lc
        .ReadFrom.AppSettings("requests"))
    .CreateLogger();
```

**Comment by andymartin** [comment]
That solved it. Thank you!
