### ISSUE TITLE
Filtering using appSettings.json

### ISSUE THREAD

**Issue by brucewilkins** [serilog/serilog-filters-expressions#21]
In a .NET Core WebAPI project, I'm able to use the following filter in code:

```c#
...
    .UseSerilog((context, loggerConfiguration) => loggerConfiguration
                        .Filter.ByExcluding("EndsWith(RequestPath, '/SomeEndpoint')")
                        .ReadFrom.Configuration(context.Configuration)
                        .Enrich.FromLogContext())
```

However when I try to do the same via the appSettings.json file it doesn't work:

```json
{
  "Serilog": {
    "Using": [ "Serilog.Filters.Expressions" ],
    "Filter": {
      "ByExcluding": "EndsWith(RequestPath, '/SomeEndpoint')"
    },
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning"
      }
    }
  }
}
```

- Is there an issue with the syntax or is this not supported? 
- Is there an easy way to do a case insensitive comparison?

Thanks

**Comment by nblumhardt** [comment]
Hi Bruce,

Your `"Filter"` block needs the array, `[`, `"Args"` and `"expression"` parts:

```json
    "Filter": [
      {
        "Name": "ByExcluding",
        "Args": {
          "expression": "EndsWith(RequestPath, '/SomeEndpoint')"
        }
      }
    ]
```

Example: https://github.com/serilog/serilog-settings-configuration/blob/dev/sample/Sample/appsettings.json#L46

To do case-insensitive comparison, use `like`:

```
          "expression": "RequestPath like '%/SomeEndpoint'"
```

HTH,
Nick

**Comment by brucewilkins** [comment]
Works great, thanks Nick!
