### ISSUE TITLE
Filter per-Sink

### ISSUE THREAD

**Issue by rcollina** [serilog/serilog-filters-expressions#27]
Hi,
I'm sorry if this has been asked before but I'm stuck.
I would like to include filter expressions for each "WriteTo" element. Namely, I'd like to filter out some messages from the console sink.
This is what I came up with but it's not working, so I'm wondering what I'm doing wrong.
Thank you!

```
{
  "Serilog": {
    "Using": [ "Serilog.Sinks.MongoDB", "Serilog.Sinks.Console", "Serilog.Filters.Expressions", "Serilog.Settings.Configuration" ],
    "MinimumLevel": "Verbose",
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "outputTemplate": "{Timestamp:o} [{Level:u3}] {Message}{NewLine}{Exception}",
          "theme": "Serilog.Sinks.SystemConsole.Themes.SystemConsoleTheme::Literate, Serilog.Sinks.Console"
        },
        "Filter": [
          {
            "Name": "ByExcluding",
            "Args": {
              "expression": "@SourceContext like '%RequestResponseLoggingMiddleware'"
            }
          }
        ]
      },
      {
        "Name": "MongoDB",
        "Args": {
          "databaseUrl": "mongodb://localhost:27017/logs",
          "collectionName": "reqlog"
        },
        "Filter": [
          {
            "Name": "ByIncludingOnly",
            "Args": {
              "expression": "@SourceContext like '%RequestResponseLoggingMiddleware' or @Level = 'Error'"
            }
          }
        ]
      }
    ]
  }
}
```

**Comment by gautelo** [comment]
@rcollina I believe the answer is sub-loggers. See https://github.com/tsimbalar/serilog-settings-comparison/blob/master/docs/README.md#sub-loggers--child-loggers.

Each sub-logger can have its own set of "Filter"'s. I agree that this feels like a workaround, but it should work.

**Comment by rcollina** [comment]
@gautelo thank you for your reply, I'll have a look asap.

**Comment by gautelo** [comment]
@rcollina Did you get it working? If so, feel free to close the issue. Always good to clean up. ;)

**Comment by rcollina** [comment]
Sorry about that, thank you!
