### ISSUE TITLE
How do I get it to work (question/bug)?

### ISSUE THREAD

**Issue by jdvor** [serilog/serilog-filters-expressions#36]
What am I doing wrong? The expression filters does not seem to work.

```
namespace ConsoleApp1.A
{
    public class ClassA { }
}

namespace ConsoleApp1.B
{
    public class ClassB { }
}

namespace ConsoleApp1
{
    using Serilog;
    using Serilog.Events;
    using System;

    public static class Program
    {
        private const string FilterExpr1 = @"@Level < 'Warning' and StartsWith(SourceContext, 'ConsoleApp1.A.')";
        private const string FilterExpr2 = @"@Level < 'Warning' and StartsWith(@SourceContext, 'ConsoleApp1.A.')";
        private const string FilterExpr3 = @"@Level < 'Warning'";

        public static void Main()
        {
            Configure1(FilterExpr3);
            //Configure2(FilterExpr3);

            var loggerA = Log.Logger.ForContext<A.ClassA>();
            loggerA.Debug("Debug A");
            loggerA.Information("Info A");
            loggerA.Warning("Warn A");
            loggerA.Error("Error A");
            loggerA.Fatal("Fatal A");

            var loggerB = Log.Logger.ForContext<B.ClassB>();
            loggerB.Debug("Debug B");
            loggerB.Information("Info B");
            loggerB.Warning("Warn B");
            loggerB.Error("Error B");
            loggerB.Fatal("Fatal B");

            Log.CloseAndFlush();
            Console.ReadKey();
        }

        private static void Configure1(string exclude)
        {
            var logCfg = new LoggerConfiguration()
                .Enrich.FromLogContext();

            logCfg.WriteTo.Console(
                restrictedToMinimumLevel: LogEventLevel.Information,
                standardErrorFromLevel: LogEventLevel.Fatal,
                outputTemplate: @"[{Timestamp:HH:mm:ss} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}");

            logCfg.Filter.ByExcluding(exclude);

            Log.Logger = logCfg.CreateLogger();
        }

        private static void Configure2(string exclude)
        {
            var logCfg = new LoggerConfiguration()
                .Enrich.FromLogContext();

            logCfg.WriteTo.Logger(lc => lc.Filter.ByExcluding(exclude))
                .WriteTo.Console(
                    restrictedToMinimumLevel: LogEventLevel.Information,
                    standardErrorFromLevel: LogEventLevel.Fatal,
                    outputTemplate: @"[{Timestamp:HH:mm:ss} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}");

            Log.Logger = logCfg.CreateLogger();
        }
    }
}
```
Neither Configure1 (global filter) nor Configure2 (per-sink) with any combination of filter expressions (FilterExpr1, FilterExpr2, FilterExpr3) have any effect on logs written to the console.
`restrictedToMinimumLevel` does work.

```
netcoreapp3.1
Serilog.Enrichers.Thread 3.1.0
Serilog.Extensions.Logging 3.0.1
Serilog.Filters.Expressions 2.1.0
Serilog.Sinks.Console 3.1.1
```

**Comment by nblumhardt** [comment]
Hi! `SourceContext` is a regular property, so the `@` isn't required in expressions. The name of `ConsoleApp1.A` is just `ConsoleApp1.A` - there's no trailing dot, so `StartsWith(SourceContext, 'ConsoleApp1.A.')` won't match - you'll need:

```
@Level < 'Warning' and (SourceContext = 'ConsoleApp1.A' or StartsWith(SourceContext, 'ConsoleApp1.A.'))
```

**Comment by jdvor** [comment]
> Hi! `SourceContext` is a regular property, so the `@` isn't required in expressions. The name of `ConsoleApp1.A` is just `ConsoleApp1.A` - there's no trailing dot, so `StartsWith(SourceContext, 'ConsoleApp1.A.')` won't match - you'll need:
> 
> ```
> @Level < 'Warning' and (SourceContext = 'ConsoleApp1.A' or StartsWith(SourceContext, 'ConsoleApp1.A.'))
> ```

I don't think that's correct - SourceContext property is `ConsoleApp1.A.ClassA` and `ConsoleApp1.B.ClassB` in this case; it's what's written to console stdout if SourceContext is in the output template. So why would you not use `StartsWith(SourceContext, 'ConsoleApp1.A.')` (dot included at the end)?

Also, it does not explain why exclusion FilterExpr3 (`@Level < 'Warning'`) is not working either.

Anyways, I've tried your suggested expression as FilterExpr4 and it does not have any effect - Info level logs for source `ConsoleApp1.A.ClassA` are not excluded.

**Comment by nblumhardt** [comment]
Ah, sorry, my mistake skimming through. I must have missed my morning coffee before replying :-D

> @Level < 'Warning'

This will be a problem, there's no ordering on warnings, you need to use `@Level in ['Verbose', 'Debug', 'Information']`.

**Comment by jdvor** [comment]
> Ah, sorry, my mistake skimming through. I must have missed my morning coffee before replying :-D
> 
> > @Level < 'Warning'
> 
> This will be a problem, there's no ordering on warnings, you need to use `@Level in ['Verbose', 'Debug', 'Information']`.

Many thanks, this one works `@"@Level in ['Verbose', 'Debug', 'Information'] and StartsWith(SourceContext, 'ConsoleApp1.A.')"` if used as "global" filter (`Configure1` setup).

Is there any way how to configure filtering per-sink?
I've tried to achieve just that in `Configure2` setup, which does not work - same expression as above.

**Comment by nblumhardt** [comment]
The overloads of `WriteTo.Conditional` should enable per-sink filtering. HTH!
