### ISSUE TITLE
Unable to Install: Detected Package Downgrade

### ISSUE THREAD

**Issue by Gabelken** [serilog/serilog-filters-expressions#37]
I'm having trouble installing via nuget package manager. It's aborting with the following error:

`Install-Package : NU1605: Detected package downgrade: Serilog from 2.9.0 to 2.8.0. Reference the package directly from the project to select a different version. `

Is this not compatible with Serilog 2.9.0?

**Comment by Gabelken** [comment]
Sorry that was user error on my part

**Comment by nblumhardt** [comment]
Thanks for the follow-up :+1:
