### ISSUE TITLE
How to escape single quotes in filters?

### ISSUE THREAD

**Issue by tomatualus** [serilog/serilog-filters-expressions#38]
Say i have a filter in my appsettings.json containg this filter 

`Contains(Message,'Executed 'Functions.ProcessData'')`

Serilog throws this exception

`ArgumentException: Syntax error (line 1, column 102): unexpected identifier `Functions`, expected `)`.`

How do i escape the ' symbol, so that i can filter out messages like 'I 'am' ' a whole' message'

**Comment by nblumhardt** [comment]
Hi! I think you need: `'Executed ''Functions.ProcessData'''` (double the single quotes to escape them).
