### ISSUE TITLE
Object filtering

### ISSUE THREAD

**Issue by Kukkimonsuta** [serilog/serilog-filters-expressions#4]
Forgive me if I missed something in documentation, but how does one filter based on object property value? I've tried following, which prints both messages:

```cs
var logger = new LoggerConfiguration()
	.Filter.ByExcluding($@"
		@Level = 'Information' and
		SomeObject.Id = 1
	")
	.WriteTo.LiterateConsole()
	.CreateLogger();

logger.Information("Do not log this {SomeObject}", new { Id = 1 });
logger.Information("Do log this {SomeObject}", new { Id = 2 });
```

**Comment by skomis-mm** [comment]
@Kukkimonsuta, you missed destructuring operator:
```csharp
logger.Information("Do not log this {@SomeObject}", new { Id = 1 });
```

**Comment by Kukkimonsuta** [comment]
I admit, this sample doesn't really make that much sense, but this is not what I need. I'm trying to filter out certain messages from EF Core logging and they are identified in `LogEvent.Properties` by

1) `SourceContext` which is a string 
2) `EventId` which is a struct (https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/EventId.cs)

I can't change how the message is formatted, so using destructuring operator is a no go.

**Comment by nblumhardt** [comment]
@Kukkimonsuta we might need a more representative example. In the case that you've shown in the first comment, the syntax of the filter is correct for general filtering of this type. Can you perhaps post the JSON representation of one of the events you're dealing with? Thanks!

**Comment by Kukkimonsuta** [comment]
Sure, this is what I get using `JsonFormatter`:

```json
{
    "Timestamp": "2017-04-08T12:49:08.3681002+02:00",
    "Level": "Information",
    "MessageTemplate": "{DbCommandLogData:l}",
    "Properties": {
        "CommandText": "SELECT [e].[Id], [e].[Subject_Id], [e].[Sender_Id], [e].[OwnerText]\r\nFROM [Messages] AS [e]\r\nWHERE ([e].[Deleted] IS NULL AND ([e].[Subject_Id] = @__subjectId_0)) AND ([e].[Source] = 2)",
        "CommandType": "Text",
        "CommandTimeout": 30,
        "Parameters": [
            "Microsoft.EntityFrameworkCore.Storage.DbParameterLogData"
        ],
        "ElapsedMilliseconds": 36,
        "DbCommandLogData": "Executed DbCommand (36ms) [Parameters=[@__subjectId_0='1'], CommandType='Text', CommandTimeout='30']\r\nSELECT [e].[Id], [e].[Subject_Id], [e].[Sender_Id], [e].[OwnerText]\r\nFROM [Messages] AS [e]\r\nWHERE ([e].[Deleted] IS NULL AND ([e].[Subject_Id] = @__subjectId_0)) AND ([e].[Source] = 2)",
        "EventId": {
            "Id": 1
        },
        "SourceContext": "Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory"
    },
    "Renderings": {
        "DbCommandLogData": [
            {
                "Format": "l",
                "Rendering": "Executed DbCommand (36ms) [Parameters=[@__subjectId_0='1'], CommandType='Text', CommandTimeout='30']\r\nSELECT [e].[Id], [e].[Subject_Id], [e].[Sender_Id], [e].[OwnerText]\r\nFROM [Messages] AS [e]\r\nWHERE ([e].[Deleted] IS NULL AND ([e].[Subject_Id] = @__subjectId_0)) AND ([e].[Source] = 2)"
            }
        ]
    }
}
```

**Comment by nblumhardt** [comment]
```csharp
	.Filter.ByExcluding("@Level = 'Information' and EventId.Id = 1")
```

Should work... No luck?

**Comment by Kukkimonsuta** [comment]
It works, thank you.

My mistake was using template string `$"@Level = 'Information' and EventId.Id = {RelationalEventId.ExecutedCommand}"` not noticing that `RelationalEventId` is an enum and not class with const ints, so the formatted string was wrong.

**Comment by viveksinghnegi7** [comment]
How can we filter s specific class or method, specially using appsettings.json
