### ISSUE TITLE
Using ByExcluding Not In from Configuration 

### ISSUE THREAD

**Issue by deathchurch** [serilog/serilog-filters-expressions#41]
I have a need to filter out multiple health endpoints similar to this:-

https://github.com/serilog/serilog-aspnetcore/issues/100

The answer:-

.Filter.ByExcluding("RequestPath not in ['/', '/ping', '/live', '/ready']")

Works well if done in code, but how can you recreate this syntax when loading from configuration? Do you have to put multiple single excluding statements?

**Comment by nblumhardt** [comment]
Hi! You should just need to write a single expression in the `"expression"` field, as in:

https://github.com/serilog/serilog-filters-expressions#json-appsettingsjson-configuration

Does it not work? It would be great to see how your configuration is constructed, if so.

**Comment by deathchurch** [comment]
Thanks for the reply @nblumhardt , the only way I could get your original answer to work was to use the following configuration:-

```json
"Serilog": {
    "Using": [ "Serilog.Settings.Configuration" ],
    "Filter": [
      {
        "Name": "ByExcluding",
        "Args": {
          "expression": "EndsWith(RequestPath, '/ping')"
        }
      },
      {
        "Name": "ByExcluding",
        "Args": {
          "expression": "EndsWith(RequestPath, '/live')"
        }
      },
      {
        "Name": "ByExcluding",
        "Args": {
          "expression": "EndsWith(RequestPath, '/ready')"
        }
      }
    ]
  }
```

Its a lot more verbose than your one liner that works well within code:- 
```csharp
.Filter.ByExcluding("RequestPath in ['/ping', '/live', '/ready']"))
```

Tried a few different combinations:-
```json
"expression": "EndsWith('RequestPath in', ['/ping', '/live', '/ready'])" - This runs but does not filter
"expression": "EndsWith(RequestPath, 'in ['/ping', '/live', '/ready']')" - This does not run
```

Actually going back to your original answer (https://github.com/serilog/serilog-aspnetcore/issues/100#issuecomment-525541904) is that not the wrong way round, does that not say exclude everything that does not appear in the list, whereas I think the OP from that thread and myself want to log everything apart from what is listed i.e. do not log for /ping, /live and /ready? In short I just changed your query from NOT IN to just IN, but it still does not work.

**Comment by skomis-mm** [comment]
Hi @deathchurch ,
try this one:
```json
"expression": "RequestPath in ['/ping', '/live', '/ready']" 
```

**Comment by deathchurch** [comment]
Excellent suggestion @skomis-mm, that does indeed do what I want, many thanks.
