### ISSUE TITLE
How to use Length for text

### ISSUE THREAD

**Issue by Marusyk** [serilog/serilog-filters-expressions#44]
Hello, could you please explain how to use `Length` for message length?

I need to include logs only if the message length is < 250.
I've tried, but no success
```
Log.Logger = new LoggerConfiguration()
                .Filter.ByIncludingOnly("@Level = 'Information' and Length(Message)<5")
                .WriteTo.Console()
                .CreateLogger();

Log.Information("Cart contains");
Log.Information("Cart");
```
In a result, no logs.

**Comment by nblumhardt** [comment]
👍 looks like you spotted that `@Message` rather than `Message` has the info you want.

Just a heads-up, https://github.com/serilog/serilog-expressions is the successor to this library, and has much better accompanying docs/examples.
