### ISSUE TITLE
Question: How to filter an array element

### ISSUE THREAD

**Issue by sb101-beep** [serilog/serilog-filters-expressions#45]
I appreciate this might be a simple question but for a given line containing an array how do I filter on the array element?

I want to make an expression that checks Type=MyService and Arguments array contains "MYARG" but I'm having some trouble with the array argument.

This is the sample line:
"HangFireJob":{"Id":"12345","CreatedAt":"2022-02-08T13:00:08.1670000","Type":"MyService","Method":"MyMethod","Arguments":["MYARG"]

This is a portion of the sample code as part of the serilog setup with a couple of different filters I have tried.  What is the correct way to write the arguments part?

```
var myFilter = "HangFireJob.Type='MyService' and 'MYARG' in HangFireJob.Arguments";
var myFilter = "HangFireJob.Type='MyService' and HangFireJob.Arguments['MYARG'] is not null";
.WriteTo.Logger(lc => lc.Filter.ByIncludingOnly(myFilter) ....
```

**Comment by nblumhardt** [comment]
The first one,

```
HangFireJob.Type = 'MyService' and 'MYARG' in HangFireJob.Arguments
```

looks correct to me. The `in` operator is case-sensitive - I don't suppose that could be the problem?
