### ISSUE TITLE
trying to specify a Filter in the appsettings.json file.

### ISSUE THREAD

**Issue by kolhapuri** [serilog/serilog-filters-expressions#9]
I am trying specify this filter in the appsettings .json file
`.Filter.ByExcluding(Matching.FromSource("Microsoft.AspNetCore.Hosting.Internal.WebHost"))`

The above syntax works when specified in c#

But trying to specify the same in a json file does not work.

"Filter": [
      {
        "Name": "ByExcluding",
        "Args": {
          "expression": "Matching.FromSource = 'Microsoft.AspNetCore.Hosting.Internal.WebHost'"
        }
      }

**Comment by brethubbard** [comment]
If anyone is looking for the solution to this, it can be found [here](https://stackoverflow.com/questions/44025992/serilog-how-do-you-specify-a-filter-expression-in-config-file).

**Comment by viveksinghnegi7** [comment]
How can we filter only to log a specific class or method?
